### ISSUE TITLE
come up with enemies

### ISSUE THREAD

**Issue by Mavodeli** [Mavodeli/spaceroguelite#4]

**Comment by KarylReyne** [comment]
### Design
Since we have a crab-themed parasite, one idea could be that we design hostile aliens based on other marine creatures (maybe more or less mechanized?). As I understand it the player will use most of the skills/upgrades for combat and because of that I think it is important that we match the enemies' combat abilities to the specific skills. What do I mean by that? For every skill, we should have at least one enemy type that is vulnerable to that skill and one that is particularly resistant. So that every skill is useful and the player has to adapt their gameplay based on what kind of enemies we throw at them. That does not necessarily mean that we have to have two enemies per one skill, one skill might be useful against a handful of enemies and be useless against just one type. Example: a skill where the player can pull enemies towards them and crush them with the claw might deal damage to most enemies, but the ability is in turn useless (or at least not very efficient) against a (Red lionfish)[https://en.wikipedia.org/wiki/Red_lionfish]-like enemy that deals massive melee damage.

**Comment by KarylReyne** [comment]
### Enemy types
- (Red lionfish)[https://en.wikipedia.org/wiki/Red_lionfish] arbitrary ranged attack, deals massive melee damage
- (Octopus)[https://en.wikipedia.org/wiki/Octopus] strong long range 'sniper' attack, but squishy
- (Mantis shrimp)[https://en.wikipedia.org/wiki/Mantis_shrimp] has a hard shell (aka bullet sponge), can shoot spears that can stun the player (think 'dwarven ballista' from Skyrim). (selected this bc wikipedia says: _mantis shrimp have powerful raptorials that are used to attack and kill prey either by spearing, stunning, or dismembering_)

**Comment by Mavodeli** [comment]
Stil Inspiration: 
[https://cdn.discordapp.com/attachments/1031949049462538257/1041370389458190396/spider.png](https://cdn.discordapp.com/attachments/1031949049462538257/1041370389458190396/spider.png)

**Comment by Mavodeli** [comment]
Stil Inspiration:
![spider](https://user-images.githubusercontent.com/61018022/201529176-f76956c7-f078-43f2-aa44-0024a6ff7d80.png)

**Comment by KarylReyne** [comment]
### Enemies Overview
- Moray eel: fast moving enemies, shoots debuff/paralysing projectile
- Anglerfish: can pull the player towards them with their luminescent fin ray and deals continuous damage by biting
- Puffer fish: small, nimble, damages with spikes (melee range)
- Mantis shrimp: hard shell, can shoot his two arms (throwing spear) at the player, cooldown to regrow arms, high dmg, high hp, also known as ‘shotgun shrimp’
Bosses may be added later ;)
